# UK visitors opening the homepage go to the UK site
[[redirects]]
  from = "/"
  to = "/uk"
  status = 302
  force = true
  conditions = {Country = ["GB"]}

[[redirects]]
  from = "/uk"
  to = "https://lawvoo-uk.vercel.app/uk"
  status = 200
  force = true

[[redirects]]
  from = "/uk/*"
  to = "https://lawvoo-uk.vercel.app/uk/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uk-static/*"
  to = "https://lawvoo-uk.vercel.app/uk-static/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/ie"
  to = "https://lawvoo-uk.vercel.app/ie"
  status = 200
  force = true

[[redirects]]
  from = "/ie/*"
  to = "https://lawvoo-uk.vercel.app/ie/:splat"
  status = 200
  force = true
